Fix LOC_CHECK_FUNC error message: backport r47301
git-svn-id: https://svn.osgeo.org/grass/grass/branches/releasebranch_6_4@47306 15284696-431f-4ddb-bdfa-cd5b030d7da7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14629,7 +14629,7 @@ else
   echo "$ac_t""no" 1>&6
 
 
-{ echo "configure: error: *** Unable to locate ." 1>&2; exit 1; }
+{ echo "configure: error: *** Unable to locate cairo_create." 1>&2; exit 1; }
 
 
 fi
