Makefile fixes for SWIG/Python
git-svn-id: https://svn.osgeo.org/grass/grass/trunk@30525 15284696-431f-4ddb-bdfa-cd5b030d7da7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -67,7 +67,7 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-curses           support Curses functionality (default: yes)"
 ac_help="$ac_help
-  --with-python[=path/python-config] enable Python support (python-config with path, \
+  --with-python[=path/python-config] enable support for Python SWIG bindings (python-config with path, \
 e.g. '--with-python=/usr/bin/python2.5-config', default: no)"
 ac_help="$ac_help
   --with-wxwidgets[=path/wx-config] enable wxWidgets support (wx-config with path, \
@@ -1018,7 +1018,7 @@ else
   if { (eval echo configure:1019: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; }; then
     for file in conftest.*; do
       case $file in
-      *.c | *.o | *.obj) ;;
+      *.$ac_ext | *.c | *.o | *.obj) ;;
       *) ac_cv_exeext=`echo $file | sed -e s/conftest//` ;;
       esac
     done
@@ -15171,6 +15171,7 @@ echo "configure:15170: checking whether to use Python" >&5
 PYTHONINC=
 PYTHONCFLAGS=
 PYTHONLDFLAGS=
+SWIG=
 USE_PYTHON=
 
 if test "$with_python" = "no" ; then
@@ -15185,7 +15186,7 @@ else
   # Extract the first word of "python-config", so it can be a program name with args.
 set dummy python-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:15189: checking for $ac_word" >&5
+echo "configure:15190: checking for $ac_word" >&5
 
 case "$PY_CONFIG" in
   /*)
@@ -15218,7 +15219,7 @@ fi
 
   if test "$PY_CONFIG" = "no" ; then
     { echo "configure: error: *** couldn't find python-config" 1>&2; exit 1; }
- fi
+  fi
 
   # With Python includes directory 
 
@@ -15230,15 +15231,15 @@ for ac_hdr in Python.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:15234: checking for $ac_hdr" >&5
+echo "configure:15235: checking for $ac_hdr" >&5
 
 cat > conftest.$ac_ext <<EOF
-#line 15237 "configure"
+#line 15238 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:15242: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:15243: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -15266,7 +15267,7 @@ fi
 done
 
 CPPFLAGS=$ac_save_cppflags
- 
+
 
   PYTHONCFLAGS=`"$PY_CONFIG" --cflags`
 
@@ -15274,7 +15275,47 @@ CPPFLAGS=$ac_save_cppflags
 
   PYTHONLDFLAGS=`"$PY_CONFIG" --ldflags`
 
+  # look for the swig program
+  # Extract the first word of "swig", so it can be a program name with args.
+set dummy swig; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:15283: checking for $ac_word" >&5
+
+case "$SWIG" in
+  /*)
+  ac_cv_path_SWIG="$SWIG" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_SWIG="$SWIG" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_SWIG="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_SWIG" && ac_cv_path_SWIG="no"
+  ;;
+esac
+SWIG="$ac_cv_path_SWIG"
+if test -n "$SWIG"; then
+  echo "$ac_t""$SWIG" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
+  if test "$SWIG" = "no" ; then
+    { echo "configure: error: *** couldn't find swig" 1>&2; exit 1; }
+  fi
+
 fi # Done checking Python
+
 
 
 
@@ -15284,7 +15325,7 @@ fi # Done checking Python
 # Enable wxWidgets support (for wxGUI)
 
 echo $ac_n "checking whether to use wxWidgets""... $ac_c" 1>&6
-echo "configure:15288: checking whether to use wxWidgets" >&5
+echo "configure:15329: checking whether to use wxWidgets" >&5
 
 WXVERSION=
 WXWIDGETSCXXFLAGS= 
@@ -15304,7 +15345,7 @@ else
   # Extract the first word of "wx-config", so it can be a program name with args.
 set dummy wx-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:15308: checking for $ac_word" >&5
+echo "configure:15349: checking for $ac_word" >&5
 
 case "$WX_CONFIG" in
   /*)
@@ -15352,7 +15393,7 @@ fi
  REQWX="2.8.1"
 
  echo $ac_n "checking wxWidgets version""... $ac_c" 1>&6
-echo "configure:15356: checking wxWidgets version" >&5
+echo "configure:15397: checking wxWidgets version" >&5
  if WXVERSION=`"$WX_CONFIG" --version`; then
    echo "$ac_t""$WXVERSION" 1>&6
  else
@@ -15375,15 +15416,15 @@ for ac_hdr in wx/wxprec.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:15379: checking for $ac_hdr" >&5
+echo "configure:15420: checking for $ac_hdr" >&5
 
 cat > conftest.$ac_ext <<EOF
-#line 15382 "configure"
+#line 15423 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:15387: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:15428: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -15419,15 +15460,15 @@ for ac_hdr in wx/wxPython/pseudodc.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:15423: checking for $ac_hdr" >&5
+echo "configure:15464: checking for $ac_hdr" >&5
 
 cat > conftest.$ac_ext <<EOF
-#line 15426 "configure"
+#line 15467 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:15431: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:15472: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -15730,6 +15771,7 @@ s%@OPENDWGLIB@%$OPENDWGLIB%g
 s%@USE_OPENDWG@%$USE_OPENDWG%g
 s%@USE_LARGEFILES@%$USE_LARGEFILES%g
 s%@PY_CONFIG@%$PY_CONFIG%g
+s%@SWIG@%$SWIG%g
 s%@PYTHONINC@%$PYTHONINC%g
 s%@PYTHONCFLAGS@%$PYTHONCFLAGS%g
 s%@PYTHONLDFLAGS@%$PYTHONLDFLAGS%g
