added

diff --git a/src/CMD/utils/setup b/src/CMD/utils/setup
--- a/src/CMD/utils/setup
+++ b/src/CMD/utils/setup
@@ -56,16 +56,81 @@ then
 fi
 udir=`$pwd`/utils
 
-
-HASX=True
-HASMotfi=TRUE
-ansi=False
-
-
-
-
-# clear all variables
-
+###################################################################### yacc
+#YACC=yacc
+#sh utils/printf %s Yacc - yet another compiler-compiler to use [$YACC]: 
+#read x
+#if test "$x" != ""
+#then
+#  YACC=$x
+#fi
+#rm -f y.tab.c
+#if $YACC utils/testyacc.y && $CC -o /tmp/$$ y.tab.c && /tmp/$$ >/dev/null <<EOF
+#10+20
+#EOF
+#then
+#sh utils/printf "%s\n" Yacc compiler looks good.
+#rm -f /tmp/$$ y.tab.c
+#else
+#sh utils/printf "%s\n" There were errors. Go find your compiler and come back...
+#rm y.tab.c
+#exit 1
+#fi
+#
+##################################################################### lex
+#LEX=lex
+#sh utils/printf %s Lex - lexical analyzer generator to use [$LEX]: 
+#read x
+#if test "$x" != ""
+#then
+#  LEX=$x
+#fi
+#
+#LEXLIB=
+#cat << 'EOF'
+##
+#Specify the lex library (if any).
+#
+#EOF
+#
+#while true
+#do
+#    sh $udir/printf %s "LEXLIB [$LEXLIB] : "
+#    read x
+#    if test "$x" = ""
+#    then
+#	break
+#    else
+#	LEXLIB=`echo "$x" | sed 's/-l *//'`
+#	if sh $udir/findlib $LEXLIB
+#	then
+#		LEXLIB=-l$LEXLIB
+#		break
+#	else
+#		echo "No such library: $LEXLIB"
+#	fi
+#    fi
+#done
+#rm -f lex.yy.c
+#if $LEX utils/testlex.l && $CC -o /tmp/$$ lex.yy.c $LEXLIB && /tmp/$$ >/dev/null <<EOF
+#uno due tre ...
+#EOF
+#then
+#sh utils/printf "%s\n" Lex compiler looks good.
+#rm -f /tmp/$$ lex.yy.c
+#else
+#sh utils/printf "%s\n" There were errors. Go find your compiler and come back...
+#rm lex.yy.c
+#exit 1
+#fi
+#
+#HASX=True
+#HASMotif=TRUE
+#ansi=False
+#
+#
+## clear all variables
+#
 ########## UNIX_BIN ##############################################
 UNIX_BIN=/usr/local/bin
 
@@ -86,6 +151,7 @@ fi
 COMPILE_FLAGS=-O ;     check_cc_flags=yes
 LDFLAGS=-s       ;     check_ld_flags=yes
 CURSES=-lcurses  ;     check_curses=yes
+INCLUDE_CURSES=  ;     check_curses=yes
 
 if test "$ansi" = "False"
 then
@@ -182,7 +248,6 @@ else
   ansi=False
 fi
 rm -f /tmp/$$
-
 
 ###intergraph/Apogee-Clipper-specific COMPILE_FLAG setting
 if test "$ansi" = True &&  test "$IGRAPH" = yes
@@ -1198,7 +1263,7 @@ check_termlib=no
 ########## CURSES ##############################################
 cat << 'EOF'
 
-Specify the curses library.
+Specify the curses library and directory with files to be included.
 EOF
 if test "$MASSCOMP" = yes && sh $udir/findlib oldcurses
 then
@@ -1232,12 +1297,37 @@ do
 	continue
     fi
 
+    echo ""
+    echo "Specify the include directory for curses (if any)"
+    echo "Enter - if you don't need a special include directory"
+    echo ""
+    sh $udir/printf %s "INCLUDE_CURSES [$INCLUDE_CURSES] : "
+    read x
+    if test "$x" != ""
+    then
+	if test "$x" != "-"
+	then
+		echo INCLUDE_CURSES $INCLUDE_CURSES
+		INCLUDE_CURSES=`echo "$x" | sed 's/-I *//'`
+		echo INCLUDE_CURSES $INCLUDE_CURSES
+		if test ! -f $INCLUDE_CURSES/curses.h
+		then
+			echo "No such file: $INCLUDE_CURSES/curses.h"
+			continue
+		fi
+		INCLUDE_CURSES=-I$INCLUDE_CURSES
+		check_curses=yes
+	else
+		INCLUDE_CURSES=
+	fi
+    fi
+
     if test "$check_curses" = yes
     then
 	echo ""
 	echo "Checking $CURSES. Please watch for any errors"
 	rm -f /tmp/$$ curses.o
-	$CC utils/curses.c $CURSES $TERMLIB -o /tmp/$$
+	$CC $INCLUDE_CURSES utils/curses.c $CURSES $TERMLIB -o /tmp/$$
 	rm -f /tmp/$$ curses.o
 	echo ""
 	echo "Check complete"
@@ -1250,9 +1340,8 @@ do
 
 done
 echo CURSES = "$CURSES"
+echo INCLUDE_CURSES = "$INCLUDE_CURSES"
 check_curses=no
-
-
 
 ########## GISBASE ###############################################
 if test "$GISBASE" = ""
@@ -1484,12 +1573,15 @@ echo ""
 echo "============================================================"
 cat << EOF | sh $udir/lineup
 CC = $CC
+YACC = $YACC
+LEX = $LEX
 COMPILE_FLAGS = $COMPILE_FLAGS
+INCLUDE_CURSES = $INCLUDE_CURSES
 LDFLAGS = $LDFLAGS
 MATHLIB = $MATHLIB
 TERMLIB = $TERMLIB
 CURSES = $CURSES
-
+LEXLIB = $LEXLIB
 XLIB = $XLIB
 XTLIB = $XTLIB
 XMLIB = $XMLIB
@@ -1580,6 +1672,11 @@ rm -f $HEAD
 echo "Creating header file"
 (
 echo CC = $CC
+echo YACC = $YACC
+echo LEX = $LEX
+echo LEXLIB = $LEXLIB
+echo INCLUDE_CURSES = $INCLUDE_CURSES
+echo ""
 echo ARCH = $ARCH
 echo ""
 echo GISBASE = $GISBASE
