you can override global setting for PostgreSQL.
	env PGSQL=NO gmake5

This makes postgresql unsupported NVIZ2.2.

And if global setting for PostgreSQL is disabled then

	env PGSQL=YES gmake5

will complain about PostgreSQL support enabled.


git-svn-id: https://svn.osgeo.org/grass/grass/branches/releasebranch_5_5@1850 15284696-431f-4ddb-bdfa-cd5b030d7da7

diff --git a/src.contrib/GMSL/NVIZ2.2/preconfig b/src.contrib/GMSL/NVIZ2.2/preconfig
--- a/src.contrib/GMSL/NVIZ2.2/preconfig
+++ b/src.contrib/GMSL/NVIZ2.2/preconfig
@@ -7,13 +7,17 @@ fi
 
 NVWISH_VER="NVWISH$1"
 
-if [ -n "$2" ]
+if [ -n "$2" -a "$PGSQL" != "no" -a "$PGSQL" != "NO" ]
 then
 	echo "*** PostgreSQL supported ***" >&2
 	cp src/query_postgr_orig.c src/query_postgr.c
 	cp scripts/panel_query_pg.tcl scripts/panel_query.tcl
 	PQ_OBJS="openvect.o getCat.o buildInfxQry.o runInfxQry.o"
 else
+	if [ -n "$PGSQL" -a "$PGSQL" != "no" -a "$PGSQL" != "NO" ]
+	then
+		echo "*** PostgreSQL library not found by global configure ***" >&2
+	fi
 	echo "*** PostgreSQL unsupported ***" >&2
 	cp src/query_postgr_dummy.c src/query_postgr.c
 	cp scripts/panel_query_orig.tcl scripts/panel_query.tcl
